import 'package:tutorialproj/model/product-model.dart';

class MyProduct {
  static List <Product> Sneakers = [
    Product(id: 1,
        name: 'Nike  Air max 200',
        category: "Trending now",
        image: 'assets/images/sneaker_02.png',
        description: "Cleanliness,versatile",
        detail:"These athletic shoes are well-suited to everyday exercises, such as light runs and mixed workouts.They have been made with good quality Mesh material that gives them durability and breathability.These shoes have a round toe shape and a cushioned insole.The EVA outsole provides comfort, grip and keeps the shoe light.",
        price: 180.00,
        quantity: 1),
    Product(id: 1,
        name: 'Addidas new born',
        category: "Out of stock",
        image: 'assets/images/sneaker_01.png',
        description: "Cleanliness,versatile",
        detail:"These athletic shoes are well-suited to everyday exercises, such as light runs and mixed workouts.They have been made with good quality Mesh material that gives them durability and breathability.These shoes have a round toe shape and a cushioned insole.The EVA outsole provides comfort, grip and keeps the shoe light.",
        price: 120.00,
        quantity: 1),
    Product(id: 1,
        name: 'Nike Orignals',
        category: "Out of stock",
        image: 'assets/images/sneaker_02.png',
        description: "Cleanliness,versatile",
        detail:"These athletic shoes are well-suited to everyday exercises, such as light runs and mixed workouts.They have been made with good quality Mesh material that gives them durability and breathability.These shoes have a round toe shape and a cushioned insole.The EVA outsole provides comfort, grip and keeps the shoe light.",
        price: 120.00,
        quantity: 1),
    Product(id: 1,
        name: 'Nike Orignals',
        category: "Out of stock",
        image: 'assets/images/sneaker_01.png',
        description: "Cleanliness,versatile",
        detail:"These athletic shoes are well-suited to everyday exercises, such as light runs and mixed workouts.They have been made with good quality Mesh material that gives them durability and breathability.These shoes have a round toe shape and a cushioned insole.The EVA outsole provides comfort, grip and keeps the shoe light.",
        price: 140.00,
        quantity: 1),
    Product(id: 1,
        name: 'Nike Orignals',
        category: "Out of stock",
        image: 'assets/images/sneaker_02.png',
        description: "Cleanliness,versatile",
        detail:"These athletic shoes are well-suited to everyday exercises, such as light runs and mixed workouts.They have been made with good quality Mesh material that gives them durability and breathability.These shoes have a round toe shape and a cushioned insole.The EVA outsole provides comfort, grip and keeps the shoe light.",
        price: 130.00,
        quantity: 1),
  ];
  static List <Product> Jackets = [
    Product(id: 1,
        name: 'Nike  Air max 200',
        category: "Trending now",
        image: 'assets/images/zipper.png',
        description: "A lightweight Jacket.",
        detail: "This aviator jacket offers timeless style and cozy comfort. Made from polyurethane leather, it features a soft shearling collar that adds warmth and a rugged appeal. The rich brown finish and tailored design make it easy to pair with anything, from jeans for a casual outing to chinos for a dressed-up look. Its roomy front pockets and a smooth zip closure make it a practical choice. Also, this men’s polyurethane leather jacket is the perfect layer to keep you looking smart.",
        price: 180.00,
        quantity: 1),
    Product(id: 1,
        name: 'Addidas new born',
        category: "Out of stock",
        image: 'assets/images/jacket.png',
        description: "Cleanliness,versatile",
        detail: "This aviator jacket offers timeless style and cozy comfort. Made from polyurethane leather, it features a soft shearling collar that adds warmth and a rugged appeal. The rich brown finish and tailored design make it easy to pair with anything, from jeans for a casual outing to chinos for a dressed-up look. Its roomy front pockets and a smooth zip closure make it a practical choice. Also, this men’s polyurethane leather jacket is the perfect layer to keep you looking smart.",
        price: 120.00,
        quantity: 1),
    Product(id: 1,
        name: 'Nike Orignals',
        category: "Out of stock",
        image: 'assets/images/zipper.png',
        description: "A lightweight Jacket.",
        detail: "This aviator jacket offers timeless style and cozy comfort. Made from polyurethane leather, it features a soft shearling collar that adds warmth and a rugged appeal. The rich brown finish and tailored design make it easy to pair with anything, from jeans for a casual outing to chinos for a dressed-up look. Its roomy front pockets and a smooth zip closure make it a practical choice. Also, this men’s polyurethane leather jacket is the perfect layer to keep you looking smart.",
        price: 120.00,
        quantity: 1),
    Product(id: 1,
        name: 'Nike Orignals',
        category: "Out of stock",
        image: 'assets/images/jacket.png',
        description: "Cleanliness,versatile",
        detail: "This aviator jacket offers timeless style and cozy comfort. Made from polyurethane leather, it features a soft shearling collar that adds warmth and a rugged appeal. The rich brown finish and tailored design make it easy to pair with anything, from jeans for a casual outing to chinos for a dressed-up look. Its roomy front pockets and a smooth zip closure make it a practical choice. Also, this men’s polyurethane leather jacket is the perfect layer to keep you looking smart.",
        price: 140.00,
        quantity: 1),
    Product(id: 1,
        name: 'Nike Orignals',
        category: "Out of stock",
        image: 'assets/images/zipper.png',
        description: "A lightweight Jacket.",
        detail: "This aviator jacket offers timeless style and cozy comfort. Made from polyurethane leather, it features a soft shearling collar that adds warmth and a rugged appeal. The rich brown finish and tailored design make it easy to pair with anything, from jeans for a casual outing to chinos for a dressed-up look. Its roomy front pockets and a smooth zip closure make it a practical choice. Also, this men’s polyurethane leather jacket is the perfect layer to keep you looking smart.",
        price: 130.00,
        quantity: 1),
  ];
  static List <Product> Watch = [
    Product(id: 1,
        name: 'Blancpain Watch',
        category: "Trending now",
        image: 'assets/images/watch1.jpg',
        description: "Beautifull,versatile",
        detail: "Blancpain Orignals is a refined gents stainless-steel watch featuring a 37mm dial and packaged in an exquisite luxury watch case",
        price: 180.00,
        quantity: 1),
    Product(id: 1,
        name: 'Rolex Orignals',
        category: "Out of stock",
        image: 'assets/images/watch2.jpg',
        description: "versatile",
        detail: "Rolex Orignals is a refined gents stainless-steel watch featuring a 37mm dial and packaged in an exquisite luxury watch case",
        price: 120.00,
        quantity: 1),
    Product(id: 1,
        name: 'Blancpain Watch',
        category: "Out of stock",
        image: 'assets/images/watch1.jpg',
        description: "Elegant,versatile",
        detail: "Blancpain Orignals is a refined gents stainless-steel watch featuring a 37mm dial and packaged in an exquisite luxury watch case",
        price: 120.00,
        quantity: 1),
    Product(id: 1,
        name: 'Rolex Orignals',
        category: "Out of stock",
        image: 'assets/images/watch2.jpg',
        description: "Cleanliness,versatile",
        detail: "Rolex Orignals is a refined gents stainless-steel watch featuring a 37mm dial and packaged in an exquisite luxury watch case.",
        price: 140.00,
        quantity: 1),
    Product(id: 1,
        name: 'Blancpain Watch',
        category: "Out of stock",
        image: 'assets/images/watch1.jpg',
        description: "Cleanliness,versatile",
        detail: "Blancpain Orignals is a refined gents stainless-steel watch featuring a 37mm dial and packaged in an exquisite luxury watch case.",
        price: 130.00,
        quantity: 1),
  ];
}